// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol_inside.proto

#ifndef PROTOBUF_protocol_5finside_2eproto__INCLUDED
#define PROTOBUF_protocol_5finside_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protocol_5finside_2eproto();
void protobuf_AssignDesc_protocol_5finside_2eproto();
void protobuf_ShutdownFile_protocol_5finside_2eproto();

class HeartBeat;

// ===================================================================

class HeartBeat : public ::google::protobuf::Message {
 public:
  HeartBeat();
  virtual ~HeartBeat();

  HeartBeat(const HeartBeat& from);

  inline HeartBeat& operator=(const HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeat& default_instance();

  void Swap(HeartBeat* other);

  // implements Message ----------------------------------------------

  HeartBeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeat& from);
  void MergeFrom(const HeartBeat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sessionNum = 1;
  inline bool has_sessionnum() const;
  inline void clear_sessionnum();
  static const int kSessionNumFieldNumber = 1;
  inline ::google::protobuf::int32 sessionnum() const;
  inline void set_sessionnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:HeartBeat)
 private:
  inline void set_has_sessionnum();
  inline void clear_has_sessionnum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sessionnum_;
  friend void  protobuf_AddDesc_protocol_5finside_2eproto();
  friend void protobuf_AssignDesc_protocol_5finside_2eproto();
  friend void protobuf_ShutdownFile_protocol_5finside_2eproto();

  void InitAsDefaultInstance();
  static HeartBeat* default_instance_;
};
// ===================================================================


// ===================================================================

// HeartBeat

// required int32 sessionNum = 1;
inline bool HeartBeat::has_sessionnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeartBeat::set_has_sessionnum() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeartBeat::clear_has_sessionnum() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeartBeat::clear_sessionnum() {
  sessionnum_ = 0;
  clear_has_sessionnum();
}
inline ::google::protobuf::int32 HeartBeat::sessionnum() const {
  // @@protoc_insertion_point(field_get:HeartBeat.sessionNum)
  return sessionnum_;
}
inline void HeartBeat::set_sessionnum(::google::protobuf::int32 value) {
  set_has_sessionnum();
  sessionnum_ = value;
  // @@protoc_insertion_point(field_set:HeartBeat.sessionNum)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_5finside_2eproto__INCLUDED
